- platform: statistics
  name: "avg_grid_power_for_10mins"
  entity_id: sensor.grid_power
  state_characteristic: mean
  max_age:
    minutes: 10
  sampling_size: 500
  precision: 1
- platform: statistics
  name: "avg_power_usage_for_10mins"
  entity_id: sensor.power_usage
  state_characteristic: mean
  max_age:
    minutes: 10
  sampling_size: 500
  precision: 1
- platform: integration
  source: sensor.solis_inverter_power_from_battery
  name: "Battery Export Power"
  unique_id: "battery_export_power"
  unit_prefix: k
  round: 2
  method: left
- platform: integration
  source: sensor.solis_inverter_power_to_battery
  name: "Battery Charge Power"
  unique_id: "battery_charge_power"
  unit_prefix: k
  round: 2
  method: left
- platform: integration
  source: sensor.solis_inverter_pv
  name: "PV Generation kWh"
  unit_prefix: k
  round: 2
  method: left
