- alias: "[blind] close office blind 10mins before sunset"
  id: "office_blind_close"
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:10:00"
  condition: []
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.office_blind
  mode: single

- alias: "[blind] open office blind after sunrise or 9am"
  id: "office_blind_open"
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:30:00"
    - platform: time
      at: "09:00:00"
  condition:
    - condition: state
      entity_id: cover.office_blind
      state: "closed"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.office_blind
  mode: single
