- alias: charge off grid inverter
  id: "offgrid_inverter_on"
  trigger:
    - platform: state
      entity_id: input_boolean.is_cheap_rate
      to: "on"
  condition: []
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.tasmota_from_inverter_plug
  mode: single

- alias: turn-off off grid inverter
  id: "offgrid_inverter_off"
  trigger:
    - platform: state
      entity_id: input_boolean.is_cheap_rate
      to: "off"
  condition: []
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.tasmota_from_inverter_plug
  mode: single
