- alias: "[Living Room] Turn on living room light when pressed on"
  id: "turn_on_living_room_light_when_pressed"
  triggers:
    - trigger: state
      entity_id: sensor.living_room_switch_action
      to: "on_press_release"
  actions:
    - action: light.turn_on
      target:
        entity_id: light.the_living_room_lights
      data:
        brightness: 230
        #xy_color: [0.472, 0.413]

- alias: "[Living Room] Turn off living room light when pressed off"
  id: "turn_off_living_room_light_when_pressed"
  triggers:
    - trigger: state
      entity_id: sensor.living_room_switch_action
      to: "off_press_release"
  actions:
    - action: light.turn_off
      target:
        entity_id: light.the_living_room_lights
