- alias: "Turn on living room light when pressed on"
  id: "turn_on_living_room_light_when_pressed"
  trigger:
    platform: state
    entity_id: sensor.living_room_switch_action
    to: "on_press"
  action:
    service: light.turn_on
    target:
      entity_id: light.the_living_room_lights
    data:
      brightness: 230
      xy_color: [0.472, 0.413]

- alias: "Turn off living room light when pressed off"
  id: "turn_off_living_room_light_when_pressed"
  trigger:
    platform: state
    entity_id: sensor.living_room_switch_action
    to: "off_press"
  action:
    service: light.turn_off
    target:
      entity_id: light.the_living_room_lights
