- alias: "[Motion] Set has_motion_downstairs_today"
  id: "set_has_motion_downstairs_today"
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_or_landing_motion
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.has_motion_downstairs_today
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.has_motion_downstairs_today

- alias: "[Motion] Reset has_motion_downstairs_today"
  id: "reset_has_motion_downstairs_today"
  trigger:
    - platform: time
      at:
        - "00:00:00"
        - "00:30:00"
        - "01:00:00"
        - "01:30:00"
        - "02:00:00"
        - "02:30:00"
        - "03:00:00"
        - "03:30:00"
        - "04:00:00"
        - "04:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.hall_or_landing_motion
        state: "off"
        for:
          minutes: 15
      - condition: numeric_state
        alias: "TV is off"
        entity_id: sensor.tv_stand_power
        below: 30
      - condition: state
        alias: "All lights are turned off"
        entity_id: light.all_lights
        state: "off"
      - condition: state
        entity_id: input_boolean.has_motion_downstairs_today
        state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.has_motion_downstairs_today
