- alias: "[Office] Set Office TRV Heat"
  id: "office_trv_heat"
  trigger:
    - platform: time
      at: "06:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.trv_office
      data:
        temperature: 20.5
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.trv_ceilidh_office
      data:
        temperature: 20.5
  mode: single

- alias: "[Office] Set Office TRV Setback"
  id: "office_trv_setback"
  trigger:
    - platform: time
      at: "18:00:00"
  condition: []
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.trv_office
          - climate.trv_ceilidh_office
      data:
        temperature: 16.0
  mode: single
