- alias: Update Energy Usage during offpeak
  trigger:
    - platform: time
      at: "23:31:00"
  action:
    service: homeassistant.update_entity
    target:
      entity_id: sensor.energy_usage_during_peak
